### ISSUE TITLE
eclectic entry issue

### ISSUE THREAD

**Issue by cdpath** [ponychicken/WebsterParser#34] opened 2022-02-03 15:17 UTC
> Ec-lec′tic, adjective [Gr. �, fr. � to pick out, choose out: cf. F. éclectique. See Eclogue, and cf. Elect.] 

There are some mis-encoded characters in `eclectic` entry.

**Comment by jeffbyrnes** [comment] 2022-02-03 22:42
Alas, this is a duplicate of #26, and not something we can fix here, b/c these errors exist in the source material.

**Closed as completed by jeffbyrnes** 2022-02-03 22:42 UTC
